name: example
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^7.2.0
  googleapis: ^16.0.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  b_scheduler:
    path: ../


flutter:
  uses-material-design: true
