name: b_scheduler
description: A customizable Flutter scheduler widget with pinch-to-zoom, infinite scrolling, Google Calendar integration, and multiple view modes.
version: 0.0.5
homepage: https://github.com/KazmaWed/b_scheduler
repository: https://github.com/KazmaWed/b_scheduler

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
