name: b_scheduler
description: A highly customizable Flutter scheduler widget with intuitive pinch-to-zoom gestures, seamless infinite scrolling, and multiple view modes (day, week, month). Features smooth timeline layouts and supports custom data sources including Google Calendar integration.
version: 0.0.2
homepage: https://github.com/KazmaWed/b_scheduler
repository: https://github.com/KazmaWed/b_scheduler

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
